new: 'new'
title: Title
description: Description
status: Status
weight: Weight 
help: Help
home: Home
class: CSS Class
class.name: CSS Class Name


allies: Allies & Partners in Crime
private.club: Private club. Guild Members only

world.designer: World Designer Panel # Title of authoring Tool
meta.title.standard: Worldbuilding and RPG Campaign Management | World Anvil 
meta.description.standard: Worldbuilding and RPG Campaign Management tools for all Storytellers, Dungeon Masters and fiction Authors

studio.homepage: Creator's Studio Homepage
studio.description.header: What's the Creator's Studio
studio.description.text: The Creator's studio is the home of all advanced customization in World Anvil. Grandmasters, and above, will be able to create and share Character sheets, Widgets, Custom Map Markers and much more as we grow.

guild.required: This feature requires a Guild Membership!
guild.required.master: This feature requres a Guild Membership of Master and above.
guild.required.grandmaster: This feature requires a Guild Membership of Grandmaster and above.


todo.your.list: To-Do List
todo.status.zero: Click on the title to Create the Article!
todo.status.one: The article is created, Unpublished and still Work in Progress
todo.status.two: The article is Published and still Work in Progress
todo.status.three: The article is Finished!

notes: Notes 
moderation: Moderation
metadata: Metadata
tags: Tags 
article.template: Article template
world: World
category: Category
author: Author
creation.date: Creation Date 
update.date: Last Update Date 
visibility: Visibility 
public: Public 
private: Private 
open: Open 
views: Views 
favorites: Favorites 
comments: Comments 
wip: Work In Progress