new: oznámení
help: Potřebuješ pomoc?
home: Domů
world.designer: Panel tvůrce světa
description: Popis
status: Stav
meta.title.standard: Správa tvoření světů a RPG kampaní | World Anvil
title: Název
weight: Důležitost
allies: Komplicové
private.club: Soukromý klub. Pouze pro členy Cechu tvůrců světů (WBG)
meta.description.standard: Nástroje správy pro světů a RPG kampaní pro všechny vypravěče,
  pány jeskyně a spisovatele
class: CSS Třídy
class.name: Název CSS třídy
studio.homepage: Domovská stránka Tvůrčí dílny
studio.description.header: Co je Tvůrčí dílna
studio.description.text: Tvůrčí studio je místem pro přizpůsobení stránek World Anvil
  pro pokročilé uživatele. Velmistři a výše budou moci vytvářet a sdílet osobní deníky,
  widgety, vlastní značky pro mapy a mnohem více.
public: Veřejné
private: Soukromé
guild.required: Tato možnost vyžaduje Členství v cechu!
guild.required.master: Tato možnost vyžaduje Členství v cechu s úrovní Mistr a vyšší.
guild.required.grandmaster: Tato možnost vyžaduje Členství v cechu s úrovní Velmistr
  a vyšší.
todo.your.list: Úkoly
todo.status.two: Článek je zveřejněn a stále je ve vývoji.
todo.status.three: Článek je dokončen!
notes: Poznámky
metadata: Metadata
tags: Štítky
article.template: Šablona pro článek
world: Svět
category: Kategorie
author: Autor
creation.date: Datum vytvoření
update.date: Datum poslední úpravy
visibility: Viditelnost
open: Otevřené
views: Zobrazení
favorites: Oblíbené
comments: Komentáře
wip: Stále ve vývoji
access.description: Je nám líto ale k této stránce nemáš přístup. Článek je nejspíš
  soukromý a ty nemáš dostatečná oprávnění k jeho zobrazení.
access.return: Vrať se, odkud jsi přišel!
access.homepage: Přejít na domovskou stránku
todo.status.zero: Kliknutím na název vytvoříš článek
todo.status.one: Článek byl vytvořen, nebyl zveřejněn a je stále ve vývoji.
moderation: Moderace
author.notes: Autorovy poznámky
access.multipass: Multipass?
username: Uživatelské jméno
state: Stát
access.activate.code: Vlož aktivační klíč
identifier: Identifikátor
studio.templates: 'Tvůrčí dílna: Šablony článků'
studio.pins: 'Tvůrčí studio: Piny'
