new: uusi
title: Otsikko
description: Kuvaus
status: Tila
weight: Painotus
help: Ohje
home: Koti
class: CSS-luokka
class.name: CSS-luokan nimi
allies: Liittolaiset & rikoskumppanit
private.club: Yksityinen. Vain killan jäsenille
world.designer: Maailmansuunnittelijoiden paneeli
meta.title.standard: Maailmanluonti ja roolipelikampanjoiden hallinta | World Anvil
meta.description.standard: Maailmanluonnin ja roolipelikampanjoiden hallintatyökalu
  kaikille tarinankertojille, luolamestareille ja fiktion kirjoittajille
studio.homepage: Suunnittelijoiden studion kotisivu
studio.description.header: Mikä on Suunnittelijoiden studio
studio.description.text: Suunnittelijoiden studio on World Anvilin kehittyneiden muokkausominaisuuksien
  koti. Jäsenet suurmestarista lähtien voiva luoda ja jakaa hahmolomakkeita, vimpaimia,
  muokattuja karttatunnuksia ja paljon muuta yhteisömme kasvaessa.
guild.required: Tämä toiminto vaatii killan jäsenyyden!
guild.required.master: Tämä toiminto vaatii vähintään kiltamestarin arvon.
guild.required.grandmaster: Tämä toiminto vaatii vähintään killan suurmestarin arvon.
todo.your.list: Tehtäväluettelo
todo.status.zero: Luo artikkeli napsauttamalla otsikkoa!
todo.status.one: Artikkeli on luotu, julkaisematon ja vielä kesken
todo.status.two: Artikkeli on julkaistu mutta vielä kesken
todo.status.three: Artikkeli on valmis!
notes: Merkintöjä
moderation: Ylläpito
metadata: Metadata
tags: Tunnisteet
article.template: Artikkelin mallipohja
world: Maailma
category: Luokka
author: Tekijä
creation.date: Luontipäivä
update.date: Viimeisin päivitys
visibility: Näkyvyys
public: Julkinen
private: Yksityinen
open: Avoin
views: Vierailuja
favorites: Suosikit
comments: Kommentit
wip: Keskeneräinen
access.multipass: Multipass?
access.description: Valitettavasti sinulla ei ole pääsyä sivulle. Luultavasti artikkeli
  on yksityinen eikä sinulle ole lukuoikeutta siihen.
access.return: Palaa takaisin!
access.homepage: Siirry kotisivulle
author.notes: Kirjoittajan muistiinpanot
studio.pins: 'Suunnittelijoiden studio: nastat'
studio.sheets: 'Suunnittelijoiden studio: lomakkeet'
access.passcode: Salasana vaaditaan
access.passcode.description: Tämä sivu on suojattu salasanalla! Jos tiedät salasanan,
  kirjoita se alapuolelle.
username: Käyttäjätunnus
state: Vaihe
access.activate: Tilauksen aktivointi
