new: Új
title: Cím
description: Leírás
status: Állapot
weight: Súly
help: Segítség
home: Kezdőlap
allies: Szövetségesek, Bűntársak
private.club: Privát klub. Csak Céhtagoknak
world.designer: Világtervező Lap
meta.title.standard: Világalkotás és RPG Kampányvezetés | World Anvil
meta.description.standard: Világalkotói, és RPG Kampányvezetői eszközök minden Mesélőnek,
  Kalandmesternek, és Szerzőnek
class: CSS Osztály
class.name: CSS Osztály Neve
studio.homepage: Alkotók Stúdiója Kezdőlap
studio.description.header: Mi az Alkotók Stúdiója
studio.description.text: Az Alkotók Stúdiója nyújt otthont a World Anvil minden fejlettebb
  testreszabási lehetőségnek. Nagymestereknek, és mindenkinek fölötte lehetősége van
  Karakterlapok, Widgetek, Egyedi Térkép Jelzők, és miegymás létrehozására, és megosztására,
  ahogy növekszünk.
guild.required: Ehhez a funkcióhoz Céhtagnak kell lenned!
guild.required.master: Ehhez a funkcióhoz legalább Mester rangú Céhtagnak kell lenned.
guild.required.grandmaster: Ehhez a funkcióhoz legalább Nagymester rangú Céhtagnak
  kell lenned.
todo.your.list: Teendők
todo.status.zero: Kattints a címre hogy Létrehozd a Cikket!
todo.status.one: A cikk létrehozva, Publikálatlan, és még mindig Átdolgozás Alatt
  áll
todo.status.two: A cikk publikálva, és még mindig Átdolgozás Alatt áll
todo.status.three: A cikk befejezve!
notes: Jegyzetek
moderation: Moderáció
metadata: Metaadatok
tags: Címkék
article.template: Cikk sablon
world: Világ
category: Kategória
author: Szerző
creation.date: Létrehozás Dátuma
update.date: Legutolsó Frissítés Dátuma
visibility: Láthatóság
public: Nyilvános
private: Privát
open: Nyílt
views: Megtekintések
favorites: Kedvencek
comments: Megjegyzések
wip: Átdolgozás Alatt
access.multipass: Világjegy?
access.description: Sajnáljuk, de nincs engedélyed megnyitni ezt az oldalt. Ez valószínűleg
  azért van, mert az oldal privát, és nem rendelkezel a megfelelő jogokkal hogy megtekintsd.
access.return: Térj vissza ahonnét jöttél!
access.homepage: A Kezdőoldalra
author.notes: A Szerző Jegyzetei
studio.pins: 'Alkotók Stúdiója: Kitűzések'
studio.sheets: 'Alkotók Stúdiója: Lapok'
access.passcode: Jelszó Szükséges
access.passcode.description: Ez az oldal jelszóval védett! Ha rendelkezel a jelszóval,
  add meg alul, hogy hozzáférj a tartalomhoz.
username: Felhasználónév
state: Állam
access.activate: Feliratkozás Aktiválása
access.activate.description: Írd be alulra a Feliratkozási kódod, hogy hozzáférj a
  tartalomhoz. Ennyire egyszerű!
access.activate.subscription: Feliratkozás Aktiválása
access.activate.code: Aktiváló Kód Megadása
access.activate.login: Be kell jelentkezned a Feliratkozásod aktiválásához!
