status: Visibilitat
notes: Apunts
tags: Etiquetes
world: Món
category: Categoria
author.notes: Notes de l'autor
new: noves
weight: Importància
title: Títol
description: Descripció
help: Ajuda
home: Pàgina d'inici
class: Classe CSS
class.name: Nom de la classe CSS
allies: Aliats i camarades
private.club: Club privat. Només membres del Gremi
world.designer: Tauler de disseny del món
meta.title.standard: Worldbuilding i gestió de campanyes de rol | World Anvil
meta.description.standard: Eines per worldbuilding i gestió de campanyes de rol per
  tots els escriptors, Dungeon Masters i autors de ficció
studio.homepage: Pàgina principal de l'estudi del creador
studio.description.header: Què és l'estudi del creador
todo.your.list: Coses per fer
todo.status.zero: Cliqueu sobre el títol per crear l'article!
todo.status.one: Aquest article està creat, no publicat i en construcció
todo.status.two: Aquest article està publicat i en construcció
todo.status.three: L'article està acabat!
moderation: Moderació
metadata: Metadades
wip: En construcció
article.template: Plantilla
author: Autor
creation.date: Data de creació
update.date: Data de l'última actualització
visibility: Visibilitat
public: Públic
private: Privat
open: Obert
views: Visites
favorites: Preferits
comments: Comentaris
access.description: Ho sento, però no podeu accedir a aquesta pàgina. Segurament és
  un article privat i no teniu els permisos necessaris per veure'l.
access.return: Torna al lloc d'on venies!
access.homepage: Vagi a la pàgina principal
