new: nuevas
title: Título
status: Visibilidad
help: Ayuda
home: Inicio
allies: Aliados y camaradas
world.designer: Panel del creador
meta.title.standard: Worldbuilding y gestión de campañas de rol | World Anvil
meta.description.standard: Herramientas de gestión para la construcción de mundos
  y campañas de rol para todos los escritores, directores de juego y autores de ficción
description: Descripción
weight: Importancia
private.club: Club privado. Solo miembros del Gremio
class: CSS Class
class.name: CSS Class Name
studio.homepage: Página de inicio del estudio del creador
studio.description.header: Qué es el estudio del creador
studio.description.text: El estudio del creador es el hogar de toda la personalización
  avanzada en World Anvil. Grandmasters y superior podrán crear y compartir fichas
  de personaje, widgets, marcadores de mapa personalizados y mucho más mientras crecemos.
guild.required: ¡Necesitas ser parte del Gremio para utilizar esta funcionalidad!
guild.required.master: Necesitas ser al menos Master del Gremio para poder utilizar
  esta funcionalidad.
guild.required.grandmaster: Necesitas ser al menos Grandmaster del Gremio para poder
  utilizar esta funcionalidad.
todo.your.list: Lista de tareas
todo.status.zero: ¡Haz clic en el título para crear el artículo!
todo.status.one: El artículo está creado, sin publicar y aún en progreso
todo.status.two: El artículo ha sido publicado y aún está en progreso
todo.status.three: ¡El artículo está terminado!
notes: Notas
moderation: Moderación
metadata: Metadatos
article.template: Plantilla
world: Mundo
category: Categoría
author: Autor
creation.date: Fecha de creación
update.date: Última edición
tags: Etiquetas
visibility: Visibilidad
public: Público
private: Privado
open: Abierto
views: Visitas
favorites: Favoritos
comments: Comentarios
wip: En proceso
access.multipass: ¿Multipase?
access.description: Lo siento mucho, pero no tienes acceso a esta página. Probablemente
  el artículo es privado y no tienes los permisos necesarios para verlo.
access.homepage: Ir a la página principal
access.return: ¡Vuelve al lugar de donde has venido!
author.notes: Notas del autor
studio.pins: 'Estudio del creador: pines'
studio.sheets: 'Estudio del creador: fichas'
access.passcode: Contraseña requerida
access.passcode.description: ¡Esta página está protegida con contraseña! Si tienes
  la contraseña, por favor introdúcela abajo para acceder al contenido.
