status: Status
new: ny
title: Titel
description: Beskrivelse
help: Hjælp
home: Hjem
weight: Vægt
private.club: Privat klub. Kun Guild medlemmer tilladt
allies: Allierede & Partnere
world.designer: Panel for Verdensdesign
meta.title.standard: Verdensbygning og RPG Kampagneledelse | World Anvil
meta.description.standard: Verdensbygning og RPG Kampagneledelsesværktøj for alle
  Historiefortællere, Dungeon Masters og Fiktionsforfattere
class: CSS Class
class.name: CSS Class Name
studio.homepage: Skaberens studie hjemmeside
studio.description.header: Hvad er skaberens studie
studio.description.text: Skaberens studie er stedet til alle avancerede tilpasninger
  i World Anvil. Grandmasters, og roller der over, vil havde mulighed for at skabe
  og dele karakter ark, Widgets, tilpasning af kort og meget mere jo større vi bliver.
guild.required: 'Denne funktion kræver Guild medlemskab '
guild.required.master: 'Denne funktion kræver et Gulid medlemskab som Master eller
  roller derover '
guild.required.grandmaster: 'Denne funktion kræver et Gulid medlemskab som Grandmaster
  eller roller derover '
todo.your.list: To-Do Liste
todo.status.zero: klik på titlen for at lave en artikel!
todo.status.one: Artiklen er lavet, ikke publiceret og bliver stadig arbejdet på
todo.status.two: 'Artiklen er publiceret og bliver stadig arbejdet på '
todo.status.three: Artiklen er færdig!
notes: Noter
metadata: Metadata
tags: Tags
article.template: 'Artikel skabelon '
world: Verden
category: 'Kategori '
author: 'Forfatter '
creation.date: Oprettelsesdato
update.date: Sidste opdaterings dato
visibility: 'Synlighed '
public: 'Offentlig '
private: 'Privat '
open: Åben
views: Visninger
favorites: Favoritter
comments: Kommentarer
wip: Arbejde der er i gang
