new: 新規
title: タイトル
description: 説明
status: 区分
weight: 加重
help: ヘルプ
home: ホーム
class: CSSクラス
class.name: CSSクラス名
allies: 関連会社・団体
private.club: プライベートクラブ。ギルドの会員のみ
world.designer: ワールド・デザイナー・パネル
meta.title.standard: ワールド作りとRPGキャンペーン管理 | World Anvil
meta.description.standard: すべての語り手、ダンジョンマスター、小説家などのためのワールド作りとRPGキャンペーン管理ツール
studio.homepage: 創作者のスタジオ・ホームページ
studio.description.header: 創作者のスタジオって何？
studio.description.text: 創作者のスタジオはWorld Anvilの中であらゆる詳細なカスタマイズ機能のある場所です。グランドマスター以上はキャラクターシート、ウィジェット、カスタム地図のマーカーなどを作成したり、シェアしたりすることだけではなく、本サイトの機能が増えるに連れてその他にもたくさんのことができるようになってきます。
guild.required: この機能はギルドへの入会が必要です！
guild.required.master: この機能はマスター以上のギルドへの入会が必要です。
guild.required.grandmaster: この機能はグランドマスター以上のギルドへの入会が必要です。
todo.your.list: やることリスト
todo.status.zero: 記事を作成するにはタイトルをクリックしてください！
todo.status.one: 記事は作り始め、未発表でまだ作成中
todo.status.two: 記事は発表済みでまだ作成中
todo.status.three: 記事は完成しました！
notes: メモ
moderation: モデレーション
metadata: メタデータ
tags: タグ
article.template: 記事テンプレート
world: ワールド
category: カテゴリ
author: 作者
creation.date: 作成日
update.date: 更新日
visibility: 公開状態
public: 公開
private: 非公開
open: オープン
views: 表示回数
favorites: お気に入り
comments: コメント
wip: 作成中
access.multipass: ムルチパス？
access.description: 申し訳ありませんが、このページにはアクセス権限がありません。原因はこの記事が非公開と設定していて表示する権利がない可能性が高いです。
access.return: 戻りましょう！
access.homepage: ホームページへ
author.notes: 作者のメモ
studio.pins: 創作者のスタジオ：ピン
studio.sheets: 創作者のスタジオ：シート
access.passcode: パスワードが必須
access.passcode.description: このページを見るにはパスワードが必要です！パスワードを下に入力した上で、内容が見られるようになります。
username: ユーザー名
state: 状態
